data_ingestion:
  bucket_name: "mlops-project-steel"
  bucket_file_name: "data.csv"
  train_ratio: 0.8

data_processing:
  feature_names:
    y_columns:
      - "Pastry"
      - "Z_Scratch"
      - "K_Scatch"
      - "Stains"
      - "Dirtiness"
      - "Bumps"
      - "Other_Faults"

model_training:
  random_search_params:
    estimator: lgbm
    n_iter: 5
    cv: 8
    verbose: 2
    random_state: 42
    n_jobs: -1
    scoring: "accuracy"
